# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-1
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/adityasamant/IdeaProjects/kind
        containerPath: /files
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp
      - containerPort: 30950
        hostPort: 5001