apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-flask-app
  name: my-flask-app-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30950
  selector:
    app: my-flask-app
  type: NodePort
status:
  loadBalancer: {}
